name: Build & Push to ACR

on:
  push:
    branches: ["master"]
  workflow_dispatch:

env:
  IMAGE_NAME: honeypot-api
  ACR_LOGIN_SERVER: aiopsjvacr.azurecr.io

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development   # ðŸ‘ˆ IMPORTANT

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker login to ACR (token-based)
        run: |
          echo "${{ secrets.ACR_TOKEN }}" | docker login ${{ env.ACR_LOGIN_SERVER }} \
            -u "${{ vars.ACR_TOKEN_NAME }}" \
            --password-stdin

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest \
            .

      - name: Push Docker image
        run: |
          docker push \
            ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
